### PR TITLE
Changed the binary from "generate" to "loom".

### PR DESCRIPTION
**Pull request by jonathanmarvens**
Please accept this pull request or pick a name that's less generic because `generate` is too generic of a name for a globally installed binary.

Thanks.

\- Jonathan

### CODE REVIEW

**Comment by coderberry** [comment]
:+1:

**Comment by ryanflorence** [comment]
Does this conflict with anything you know of?

**Comment by coderberry** [comment]
Not that I know of but I do like having the command be something that is specific to the library itself

**Comment by jonathanmarvens** [comment]
@rpflorence Nope, but as @cavneb mentioned, the name of the binary is just too generic ... maybe `loomgen` (TBH, I don't quite like this one) or `loom` ... just something that's a bit closer to the library.

**Comment by ryanflorence** [comment]
At the moment loom has two binaries (though the other is in a separate repo, its installed as a peer dependency): `generate` and `originate`; they go well together.

I would have named the library "generate" but it is occupied by an [obscure module on npm](https://npmjs.org/package/generate).

Finally, don't install it globally, just have `node_modules/.bin` in your path. There is no reason to install this globally if you find some other binary named `generate`.

I guess I need a stronger argument to change it than "I think its too generic" especially when npm allows you to install things locally.

Feel free to reopen if you think I'm completely off-base.

**Pull request closed without merging**
